### ISSUE TITLE
Allow Other is not showing new field

### ISSUE THREAD

**Issue by dedenbangkit** [akvo/akvo-webform#61]
## TODO

- [x] Allow other in option component
- [x] Allow other in multiple option component
- [x] Attach isOther object in request
- [x] Modify pydantic to accept isOther
